### ISSUE TITLE
WTF Bug...

### ISSUE THREAD

**Issue by desaura** [desaura/vipsace#3]
An unknown bug in file,
```
\assets\incl\member.html
```
Click/Touch is not being detected when we click on **Button** with class **_menu_button_** inside the **div** with class of **_hero-member_** on _line 24_.
#### Javascript used for above purpose
```
    $('.menu-button').on('click', function(){
        $('.menu').css("top","0%");
    });
```
JS file is located at 
```
\js\main.js
```

**Comment by srijitcoder** [comment]
solved

it's because your 
.hero-text div is covering the button
just took away top:-130px; (not req u have also not included in index.html)

**Comment by desaura** [comment]
Issue solved by @srijitcoder
